=== code-warrior/assignment-2--databases--cs-365--fall-2020/student.dtd
<!ELEMENT College_Directory (student+)>
        <!ATTLIST College_Directory> <!--This creates the directory of students in the college. -->
<!ELEMENT student (first_name, middle_name, last_name, preferred_name, student_id, email, phone, year,
    gpa, major, minor, student_status, advisor, date_of_initial_enrollment, graduation_date) #PCDATA>   <!-- This contains all the information that each student will have to identify them.-->
   <!ATTLIST student id ID #REQUIRED>   <!-- This is where the student is given a unique identifier so two students are not the same. -->
<!--<!ELEMENT CDATA EMPTY> -->
<!ELEMENT first_name ANY>   <!-- This is where the first name of the student is placed. -->
<!ELEMENT middle_name ANY>  <!-- This is where the middle name of the student is placed. -->
<!ELEMENT last_name ANY>    <!-- This is where the last name of the student is placed. -->
<!ELEMENT preferred_name ANY>   <!-- This is where the preferred name of the student is placed. -->
<!ELEMENT student_id ANY>   <!-- This is where the student id of the student is placed. -->
<!ELEMENT email ANY>   <!-- This is where the email of the student is placed. -->
<!ELEMENT phone ANY>   <!-- This is where the phone number of the student is placed. -->
<!ELEMENT year ANY>   <!-- This is where the year of the student is placed. -->
<!ELEMENT gpa ANY>   <!-- This is where the gpa of the student is placed. -->
<!ELEMENT major ANY>   <!-- This is where the major of the student is placed. -->
<!ELEMENT minor ANY>   <!-- This is where the minor of the student is placed. -->
<!ELEMENT student_status ANY>   <!-- This is where the student status of the student is placed. -->
<!ELEMENT advisor ANY>   <!-- This is where the advisor of the student is placed. -->
<!ELEMENT date_of_initial_enrollment ANY>   <!-- This is where the date of initial enrollment of the student is placed. -->
<!ELEMENT graduation_date ANY> <!-- This is where the graduation date of the student is placed. -->

=== code-warrior/assignment-2--databases--cs-365--fall-2020/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="css\style.css"?>
<!DOCTYPE College_Directory SYSTEM "dtd/student.dtd">
<College_Directory>
    <student id="19593544">
        <first_name>First name: Henry</first_name>
        <middle_name>Middle name: Peter</middle_name>
        <last_name>Last name: Collins</last_name>
        <preferred_name>Preferred name: Henry</preferred_name>
        <student_id>Student ID: 19593544</student_id>
        <email>Email: Collins@hartford.edu</email>
        <phone>Phone: 413-668-5774</phone>
        <year>Year: None</year>
        <gpa> GPA: 3.80</gpa>
        <major>Major: Computer Science</major>
        <minor>Minor: Math</minor>
        <student_status>Student status: graduated</student_status>
        <advisor>Advisor: Professor Russell</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2015</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2019</graduation_date>
    </student>
    <student id="19368854">
        <first_name>First name: Mary</first_name>
        <middle_name>Middle name: Nicole</middle_name>
        <last_name>Last name: Daniels</last_name>
        <preferred_name>Preferred name: Mary</preferred_name>
        <student_id>Student ID: 19368854</student_id>
        <email>Email: Mdaniels@hartford.edu</email>
        <phone>Phone: 860-441-2556</phone>
        <year>Year: None</year>
        <gpa>GPA: 3.66</gpa>
        <major>Major: Computer Engineering</major>
        <minor>Minor: Math</minor>
        <student_status>Student status: graduated</student_status>
        <advisor>Advisor: Professor Eppes</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2013</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2017</graduation_date>
    </student>
    <student id="19778028">
        <first_name>First name: Maria</first_name>
        <middle_name>Middle name: Christina</middle_name>
        <last_name>Last name: Davis</last_name>
        <preferred_name>Preferred name: Maria</preferred_name>
        <student_id>Student ID: 19778028</student_id>
        <email>Email: Mdavis@hartford.edu</email>
        <phone>Phone: 860-223-1886</phone>
        <year>Year: First-year</year>
        <gpa>GPA: 3.70</gpa>
        <major>Major: Computer Science</major>
        <minor>Minor: None</minor>
        <student_status>Student status: full-time</student_status>
        <advisor>Advisor: Professor Russell</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2017</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2021</graduation_date>
    </student>
    <student id="19649173">
        <first_name>First name: Michelle</first_name>
        <middle_name>Middle name: Patricia</middle_name>
        <last_name>Last name: Ford</last_name>
        <preferred_name>Preferred name: Michelle</preferred_name>
        <student_id>Student ID: 19649173</student_id>
        <email>Email: Miford@hartford.edu</email>
        <phone>Phone: 413-743-5569</phone>
        <year>Year: Second-year</year>
        <gpa>GPA: 3.80</gpa>
        <major>Major: Computer Science</major>
        <minor> Minor: Math</minor>
        <student_status>Student status: full-time</student_status>
        <advisor>Advisor: Professor Russell</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2016</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2020</graduation_date>
    </student>
    <student id="19742866">
        <first_name>First name: Robert</first_name>
        <middle_name>Middle name: Michael</middle_name>
        <last_name>Last name: Foreman</last_name>
        <preferred_name>Preferred name: Bob</preferred_name>
        <student_id>Student ID: 19742866</student_id>
        <email>Email: Foreman@hartford.edu</email>
        <phone>Phone: 413-849-7681</phone>
        <year>Year: Fourth-year</year>
        <gpa>GPA: 3.55</gpa>
        <major>Major: Computer Engineering</major>
        <minor>Minor: Math</minor>
        <student_status>Student status: withdrawn</student_status>
        <advisor>Advisor: Professor Eppes</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2017</date_of_initial_enrollment>
        <graduation_date>Graduation date: December 2021</graduation_date>
    </student>
    <student id="19638469">
        <first_name>First name: Elizabeth</first_name>
        <middle_name>Middle name: Jane</middle_name>
        <last_name>Last name: Johnson</last_name>
        <preferred_name>Preferred name: Liz</preferred_name>
        <student_id>Student ID: 19638469</student_id>
        <email>Email: Johnson@hartford.edu</email>
        <phone>Phone: 413-461-7253</phone>
        <year>Year: Second-year</year>
        <gpa>GPA: 3.70</gpa>
        <major>Major: Computer Science</major>
        <minor> Minor: Math</minor>
        <student_status>Student status: full-time</student_status>
        <advisor>Advisor: Professor Rosiene</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2016</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2020</graduation_date>
    </student>
    <student id="19467998">
        <first_name>First name: Danielle</first_name>
        <middle_name>Middle name: Barbara</middle_name>
        <last_name>Last name: Kincaid</last_name>
        <preferred_name>Preferred name: Danielle</preferred_name>
        <student_id>Student ID: 19467998</student_id>
        <email>Email: Kincaid@hartford.edu</email>
        <phone>Phone: 203-336-9742</phone>
        <year>Year: First-year</year>
        <gpa>GPA: 4.00</gpa>
        <major>Major: Computer Engineering</major>
        <minor>Minor: None</minor>
        <student_status>Student status: full-time</student_status>
        <advisor>Advisor: Professor Yu</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2017</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2021</graduation_date>
    </student>
    <student id="19854366">
        <first_name>First name: Richard</first_name>
        <middle_name>Middle name: David</middle_name>
        <last_name>Last name: Manning</last_name>
        <preferred_name>Preferred name: Dave</preferred_name>
        <student_id>Student ID: 19854366</student_id>
        <email>Email: Rimann@hartford.edu</email>
        <phone>Phone: 203-249-1154</phone>
        <year>Year: Second-year</year>
        <gpa>GPA: 3.67</gpa>
        <major>Major: Computer Science</major>
        <minor>Minor: None</minor>
        <student_status>Student status: full-time</student_status>
        <advisor>Advisor: Professor Becker</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2018</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2022</graduation_date>
    </student>
    <student id="19678245">
        <first_name>First name: Richard</first_name>
        <middle_name>Middle name: James</middle_name>
        <last_name>Last name: Manning</last_name>
        <preferred_name>Preferred name: Rick</preferred_name>
        <student_id>Student ID: 19678245</student_id>
        <email> Email: Rmanning@hartford.edu</email>
        <phone> Phone: 860-197-3492</phone>
        <year>Year: None</year>
        <gpa>GPA: 3.85</gpa>
        <major>Major: Computer Science</major>
        <minor>Minor: Math</minor>
        <student_status>Student status: Graduated</student_status>
        <advisor>Advisor: Professor Rosiene</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2016</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2020</graduation_date>
    </student>
    <student id="19793554">
        <first_name>First name: Nancy</first_name>
        <middle_name>Middle name: Leslie</middle_name>
        <last_name>Last name: Martinez</last_name>
        <preferred_name>Preferred name: Nancy</preferred_name>
        <student_id>Student ID: 19793554</student_id>
        <email>Email: Nmartinez@hartford.edu</email>
        <phone>Phone: 413-284-3755</phone>
        <year>Year: First-year</year>
        <gpa>GPA: 3.90</gpa>
        <major>Major: Computer Engineering</major>
        <minor>Minor: None</minor>
        <student_status>Student status: part-time</student_status>
        <advisor>Advisor: Professor Eppes</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2017</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2022</graduation_date>
    </student>
    <student id="19468536">
        <first_name>First name: Robert</first_name>
        <middle_name>Middle name: James</middle_name>
        <last_name>Last name: Nicholas</last_name>
        <preferred_name>Preferred name: Rob</preferred_name>
        <student_id>Student ID: 19468536</student_id>
        <email>Email: Rnicholas@hartford.edu</email>
        <phone>Phone: 860-469-8731</phone>
        <year>Year: First-year</year>
        <gpa>GPA: 3.80</gpa>
        <major>Major: Computer Engineering</major>
        <minor>Minor: Math</minor>
        <student_status>Student status: full-time</student_status>
        <advisor>Advisor: Professor Eppes</advisor>
        <date_of_initial_enrollment>Date of initial enrollment: September 2014</date_of_initial_enrollment>
        <graduation_date>Graduation date: May 2018</graduation_date>
    </student>
    <student id="19682391">
        <first_name>First name: Anna</first_name>
        <middle_name>Middle name: Charlotte</middle_name>
        <last_name>Last name: Nichols</last_name>
